version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12
  pre_build:
    commands:
      - echo installing dependencies
      - yarn install
artifacts:
  files:
    - imagedefinitions.json
